openapi: 3.0.0
info:
  title: 사진데이터 분석하여 유사 매물 추천
  version: '1.0'
servers:
  - url: /estate

paths:
  /by_gpt:
    post:
      summary: 이미지를 분석하여 입지정보를 분석해 준다.
      operationId: estate.by_gpt
      responses:
        '200':
          description: A list of street addresses
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid input
        '500':
          description: Internal server error
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                img_file:
                  type: string
                  format: binary
                  description: The image file to process
  /by_vit:
    post:
      summary: 이미지를 분석하여 입지정보를 분석해 준다.
      operationId: estate.by_vit
      responses:
        '200':
          description: A list of street addresses
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid input
        '500':
          description: Internal server error
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                img_file:
                  type: string
                  format: binary
                  description: The image file to process
