openapi: 3.0.0
info:
  title: 사진데이터 분석하여 유사 매물 추천
  version: '1.0'
servers:
  - url: /estate

paths:
  /predict:
    post:
      summary: 이미지를 분석하여 유사한 매물 주소 목록을 리턴한다.
      operationId: estate.predict
      responses:
        '200':
          description: A list of street addresses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - "123 Main St, Springfield, IL"
                  - "456 Elm St, Shelbyville, IL"
        '400':
          description: Invalid input
        '500':
          description: Internal server error
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                img_file:
                  type: string
                  format: binary
                  description: The image file to process
