openapi: 3.0.0
info:
  title: 사진데이터 분석하여 유사 매물 추천
  version: '1.0'
servers:
  - url: /estate

paths:
  /predict:
    post:
      summary: 현재 진동데이터에 대한 평가 예측(정상/이상)
      operationId: src.sensing.main.predict
      responses:
        '200':
          description: 예측 결과
          content:
            '*/*':
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
